apiVersion: v1
kind: Pod

metadata:
  name: segment3d-pod

spec:
  restartPolicy: OnFailure

  volumes:
    - name: pvol-nadhif
      persistentVolumeClaim:
        claimName: pvclaim-nadhif

  containers:
    - name: segment3d-container
      image: "nvcr.io/nvidia/pytorch:21.04-py3"

      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 10; done"]

      volumeMounts:
        - mountPath: "/workspace"
          name: pvol-nadhif

      resources:
        requests:
          ephemeral-storage: "128Gi"
          memory: "24Gi"
        limits:
          ephemeral-storage: "128Gi"
          memory: "24Gi"
